const WorkspaceAction = {
    REQUEST_GET_ALL_PROJECTS: "REQUEST_GET_ALL_PROJECTS",
    SUCCESS_GET_ALL_PROJECTS : 'SUCCESS_GET_ALL_PROJECTS',
    FAIL_GET_ALL_PROJECTS : ' FAIL_GET_ALL_PROJECTS',

    REQUEST_CREAT_NEW_PROJECT: "REQUEST_CREAT_NEW_PROJECT",
    SUCCESS_CREAT_NEW_PROJECT: "SUCCESS_CREAT_NEW_PROJECT",
    FAIL_CREAT_NEW_PROJECT: "FAIL_CREAT_NEW_PROJECT",

    REQUEST_GET_DETAIL_PROJECT: "REQUEST_GET_DETAIL_PROJECT",
    SUCCESS_GET_DETAIL_PROJECT: "SUCCESS_GET_DETAIL_PROJECT",
    FAIL_GET_DETAIL_PROJECT: "FAIL_GET_DETAIL_PROJECT",

    REQUEST_GET_LIST_CARDS: 'REQUEST_GET_LIST_CARDS',
    SUCCESS_GET_LIST_CARDS: 'SUCCESS_GET_LIST_CARDS',
    FAIL_GET_LIST_CARDS: 'FAIL_GET_LIST_CARDS',

    REQUEST_GET_LIST_MEMBERS:'REQUEST_GET_LIST_MEMBERS',
    SUCCESS_GET_LIST_MEMBERS:'SUCCESS_GET_LIST_MEMBERS',
    FAIL_GET_LIST_MEMBERS:'FAIL_GET_LIST_MEMBERS',

    REQUEST_INVITE_MEMBER:'REQUEST_INVITE_MEMBER',
    SUCCESS_INVITE_MEMBER:'SUCCESS_INVITE_MEMBER',
    FAIL_INVITE_MEMBER:'FAIL_INVITE_MEMBER',

    REQUEST_DELETE_PROJECT: 'REQUEST_DELETE_PROJECT',
    SUCCESS_DELETE_PROJECT: 'SUCCESS_DELETE_PROJECT',
    FAIL_DELETE_PROJECT: 'FAIL_DELETE_PROJECT',

    REQUEST_GET_MEMBERS_WITH_TASK:'REQUEST_GET_MEMBERS_WITH_TASK',
    SUCCESS_GET_MEMBERS_WITH_TASK:'SUCCESS_GET_MEMBERS_WITH_TASK',

    REQUEST_GET_LIST_LABELS_WORKSPACE: 'REQUEST_GET_LIST_LABELS_WORKSPACE',
    SUCCESS_GET_LIST_LABELS_WORKSPACE: 'SUCCESS_GET_LIST_LABELS_WORKSPACE',

    REQUEST_GET_RECENTLY_PROJECT:'REQUEST_GET_RECENTLY_PROJECT',
    SUCCESS_GET_RECENTLY_PROJECT:'SUCCESS_GET_RECENTLY_PROJECT',

    REQUEST_GET_LIST_MEMBER_WITH_TASK:'REQUEST_GET_LIST_MEMBER_WITH_TASK',
    SUCCESS_GET_LIST_MEMBER_WITH_TASK:'SUCCESS_GET_LIST_MEMBER_WITH_TASK',

    REQUEST_REMOVE_MEMBER_OF_WORKSPACE:'REQUEST_REMOVE_MEMBER_OF_WORKSPACE',
    SUCCESST_REMOVE_MEMBER_OF_WORKSPACE:'SUCCESST_REMOVE_MEMBER_OF_WORKSPACE',
    
    REQUEST_LEAVE_WORKSPACE:'REQUEST_LEAVE_WORKSPACE',
    SUCCESS_LEAVE_WORKSPACE:'SUCCESS_LEAVE_WORKSPACE',

   
}
export default WorkspaceAction;