const TaskAction = {
    REQUEST_CREATE_TASK:"REQUEST_CREATE_TASK",
    SUCCESS_CREATE_TASK:"SUCCESS_CREATE_TASK",
    FAIL_CREATE_TASK:"FAIL_CREATE_TASK",

    REQUEST_GET_DETAIL_TASK: 'REQUEST_GET_DETAIL_TASK',
    SUCCESS_GET_DETAIL_TASK: 'SUCCESS_GET_DETAIL_TASK',
    FAIL_GET_DETAIL_TASK: 'FAIL_GET_DETAIL_TASK',
    
    REQUEST_MOVE_TASK: 'REQUEST_MOVE_TASK',
    SUCCESS_MOVE_TASK: 'SUCCESS_MOVE_TASK',
    FAIL_MOVE_TASK: 'FAIL_MOVE_TASK',

    REQUEST_DELETE_TASK:'REQUEST_DELETE_TASK',
    SUCCESS_DELETE_TASK:'SUCCESS_DELETE_TASK',
    FAIL_DELETE_TASK:'FAIL_DELETE_TASK',

    REQUEST_ASSIGN_TASK_MEMBERS: 'REQUEST_ASSIGN_TASK_MEMBERS',
    SUCCESS_ASSIGN_TASK_MEMBERS: 'SUCCESS_ASSIGN_TASK_MEMBERS',
    DELETE_ASSIGN_TASK_MEMBERS: 'DELETE_ASSIGN_TASK_MEMBERS',


    REQUEST_DELETE_LABEL: 'REQUEST_DELETE_LABEL',
    SUCCESS_DELETE_LABEL: 'SUCCESS_DELETE_LABEL',

    REQUEST_CREATE_NEW_LABEL:'REQUEST_CREATE_NEW_LABEL',
    SUCCESS_CREATE_NEW_LABEL:'SUCCESS_CREATE_NEW_LABEL',
    FAIL_CREATE_NEW_LABEL:'FAIL_CREATE_NEW_LABEL',

    REQUEST_ADD_LABEL: 'REQUEST_ADD_LABEL',
    SUCCESS_ADD_LABEL: 'SUCCESS_ADD_LABEL',
    FAIL_ADD_LABEL: 'FAIL_ADD_LABEL',

    REQUEST_EDIT_TASK:'REQUEST_EDIT_TASK',
    SUCCESS_EDIT_TASK:'SUCCESS_EDIT_TASK',

    REQUEST_POST_COMMENT:'REQUEST_POST_COMMENT',
    SUCCESS_POST_COMMENT:'SUCCESS_POST_COMMENT',

    REQUEST_DELETE_COMMENT_TASK: 'REQUEST_DELETE_COMMENT_TASK',
    SUCCESS_DELETE_COMMENT_TASK: 'SUCCESS_DELETE_COMMENT_TASK',

    REQUEST_GET_TASKS_BY_MEMBER: 'REQUEST_GET_TASKS_BY_MEMBER',
    SUCCESS_GET_TASKS_BY_MEMBER: 'SUCCESS_GET_TASKS_BY_MEMBER',

    REQUEST_ACCEPT_EXTEND_DATE:'REQUEST_ACCEPT_EXTEND_DATE',
    SUCCESS_ACCEPT_EXTEND_DATE:'SUCCESS_ACCEPT_EXTEND_DATE',

    REQUEST_REJECT_EXTEND_DATE:'REQUEST_REJECT_EXTEND_DATE',
    SUCCESS_REJECT_EXTEND_DATE:'SUCCESS_REJECT_EXTEND_DATE',

    REQUEST_GET_UPCOMING_TASKS:'REQUEST_GET_UPCOMING_TASKS',
    SUCCESS_GET_UPCOMING_TASKS:'SUCCESS_GET_UPCOMING_TASKS',

    //SUBTASK
    REQUEST_CREATE_SUBTASK:'REQUEST_CREATE_SUBTASK',
    SUCCESS_CREATE_SUBTASK:'SUCCESS_CREATE_SUBTASK',
    REQUEST_CHANGE_STATUS_SUBTASK:'REQUEST_CHANGE_STATUS_SUBTASK',
    SUCCESS_CHANGE_STATUS_SUBTASK:'SUCCESS_CHANGE_STATUS_SUBTASK',
    REQUEST_DELETE_SUBTASK:'REQUEST_DELETE_SUBTASK',
    SUCCESS_DELETE_SUBTASK:'SUCCESS_DELETE_SUBTASK',

    REQUEST_EDIT_SUBTASK:'REQUEST_EDIT_SUBTASK',
    SUCCESS_EDIT_SUBTASK:'SUCCESS_EDIT_SUBTASK',

    REQUEST_EXTEND_DUE_DATE: 'REQUEST_EXTEND_DUE_DATE',
    SUCCESS_EXTEND_DUE_DATE: 'SUCCESS_EXTEND_DUE_DATE',
}
export default TaskAction;