const AdminAction = {
    REQUEST_ADMIN_REGISTER:"REQUEST_ADMIN_REGISTER",
    SUCCESS_ADMIN_REGISTER:"SUCCESS_ADMIN_REGISTER",
    FAIL_ADMIN_REGISTER : 'FAIL_ADMIN_REGISTER',

    REQUEST_ADMIN_LOGIN : "REQUEST_ADMIN_LOGIN",
    SUCCESS_ADMIN_LOGIN: "SUCCESS_ADMIN_LOGIN",
    FAIL_ADMIN_LOGIN: "FAIL_ADMIN_LOGIN",

    REQUEST_GET_LIST_USERS:'REQUEST_GET_LIST_USERS',
    SUCCESS_GET_LIST_USERS:'SUCCESS_GET_LIST_USERS',

    REQUEST_GET_LIST_PROJECTS_OF_USER: 'REQUEST_GET_LIST_PROJECTS_OF_USER',
    SUCCESS_GET_LIST_PROJECTS_OF_USER: 'SUCCESS_GET_LIST_PROJECTS_OF_USER',

    REQUEST_EDIT_PROFILE_ADMIN: 'REQUEST_EDIT_PROFILE_ADMIN',
    SUCCESS_EDIT_PROFILE_ADMIN: 'SUCCESS_EDIT_PROFILE_ADMIN',

    REQUEST_GET_DETAIL_PROFILE_ADMIN:'REQUEST_GET_DETAIL_PROFILE_ADMIN',
    SUCCESS_GET_DETAIL_PROFILE_ADMIN:'SUCCESS_GET_DETAIL_PROFILE_ADMIN',

    REQUEST_UPLOAD_AVATAR_ADMIN:'REQUEST_UPLOAD_AVATAR_ADMIN',
    SUCCESS_UPLOAD_AVATAR_ADMIN:'SUCCESS_UPLOAD_AVATAR_ADMIN',
    
    REQUEST_UPLOAD_AVATAR_ADMIN_TO_CLOUDINARY:'REQUEST_UPLOAD_AVATAR_ADMIN_TO_CLOUDINARY',
    SUCCESS_UPLOAD_AVATAR_AMDIN_TO_CLOUDINARY:'SUCCESS_UPLOAD_AVATAR_AMDIN_TO_CLOUDINARY',

    REQUEST_UPLOAD_AVATAR_AMDIN_TO_SERVER:'REQUEST_UPLOAD_AVATAR_AMDIN_TO_SERVER',
    SUCCESS_UPLOAD_AVATAR_AMDIN_TO_SERVER:'SUCCESS_UPLOAD_AVATAR_AMDIN_TO_SERVER',
}
export default AdminAction;
