const signalRActions = {
    INITIALIZE_SIGNALR_CONNECTION:"INITIALIZE_SIGNALR_CONNECTION",
    CLOSE_SIGNALR_CONNECTION:'CLOSE_SIGNALR_CONNECTION',
    SET_SIGNALR_CONNECTION:'SET_SIGNALR_CONNECTION'
}
export default signalRActions;
