const UserAction = {
    REQUEST_REGISTER:"REQUEST_REGISTER",
    SUCCESS_REGISTER:"SUCCESS_REGISTER",
    FAIL_REGISTER : 'FAIL_REGISTER',

    REQUEST_LOGIN : "REQUEST_LOGIN",
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    FAIL_LOGIN: "FAIL_LOGIN",

    REQUEST_EDIT_PROFILE: 'REQUEST_EDIT_PROFILE',
    SUCCESS_EDIT_PROFILE: 'SUCCESS_EDIT_PROFILE',

    REQUEST_GET_DETAIL_PROFILE:'REQUEST_GET_DETAIL_PROFILE',
    SUCCESS_GET_DETAIL_PROFILE:'SUCCESS_GET_DETAIL_PROFILE',

    REQUEST_UPLOAD_AVATAR:'REQUEST_UPLOAD_AVATAR',
    SUCCESS_UPLOAD_AVATAR:'SUCCESS_UPLOAD_AVATAR',
    
    REQUEST_UPLOAD_AVATAR_TO_CLOUDINARY:'REQUEST_UPLOAD_AVATAR_TO_CLOUDINARY',
    SUCCESS_UPLOAD_AVATAR_TO_CLOUDINARY:'SUCCESS_UPLOAD_AVATAR_TO_CLOUDINARY',

    REQUEST_UPLOAD_AVATAR_TO_SERVER:'REQUEST_UPLOAD_AVATAR_TO_SERVER',
    SUCCESS_UPLOAD_AVATAR_TO_SERVER:'SUCCESS_UPLOAD_AVATAR_TO_SERVER',
}
export default UserAction;
