const UserAction = {
    REQUEST_REGISTER:"REQUEST_REGISTER",
    SUCCESS_REGISTER:"SUCCESS_REGISTER",
    FAIL_REGISTER : 'FAIL_REGISTER',

    REQUEST_LOGIN : "REQUEST_LOGIN",
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    FAIL_LOGIN: "FAIL_LOGIN"
}
export default UserAction;
